const PREFIX="TEST_";

export const REQUEST_TREE_DATA = `${PREFIX}REQUEST_TREE_DATA`;
export const RECEIVE_TREE_DATA = `${PREFIX}RECEIVE_TREE_DATA`;

export const REQUEST_VERSION_CONTROL_DATA = `${PREFIX}REQUEST_VERSION_CONTROL_DATA`;
export const RECEIVE_VERSION_CONTROL_DATA = `${PREFIX}RECEIVE_VERSION_CONTROL_DATA`;