const PREFIX="LAYOUT_";

export const RECEIVE_MENU_TOGGLE = `${PREFIX}RECEIVE_MENU_TOGGLE`;

export const REQUEST_LOG_OUT = `${PREFIX}REQUEST_LOG_OUT`;

export const RECEIVE_POST_DRAWER_TOGGLE = `${PREFIX}RECEIVE_POST_DRAWER_TOGGLE`;