const PREFIX="LAYOUT_";

export const REQUEST_LOG_OUT = `${PREFIX}REQUEST_LOG_OUT`;

export const REQUEST_DELIVERED_POST = `${PREFIX}REQUEST_DELIVERED_POST`;
export const RECEIVE_DELIVERED_POST_REGISTER = `${PREFIX}RECEIVE_DELIVERED_POST_REGISTER`;

export const RECEIVE_MENU_TOGGLE = `${PREFIX}RECEIVE_MENU_TOGGLE`;

export const RECEIVE_POST_DRAWER_TOGGLE = `${PREFIX}RECEIVE_POST_DRAWER_TOGGLE`;