const PREFIX="LAYOUT_";

export const POST_REGISTER = `${PREFIX}POST_REGISTER`;

export const RECEIVE_POST_DRAWER_TOGGLE = `${PREFIX}RECEIVE_POST_DRAWER_TOGGLE`;

export const REQUEST_POST_REGISTER = `${PREFIX}REQUEST_POST_REGISTER`;