const PREFIX="POST_";

export const POST_REGISTER = `${PREFIX}POST_REGISTER`;

export const REQUEST_POST_REGISTER = `${PREFIX}REQUEST_POST_REGISTER`;
export const RECEIVE_POST_REGISTER = `${PREFIX}RECEIVE_POST_REGISTER`;

