const PREFIX="ENTRY_";

export const REQUEST_LOGIN = `${PREFIX}REQUEST_LOGIN`;

export const REQUEST_USER_REGISTRATION = `${PREFIX}REQUEST_USER_REGISTRATION`;
export const RECEIVE_USER_REGISTRATION = `${PREFIX}RECEIVE_USER_REGISTRATION`;