const PREFIX="ENTRY_";

export const REQUEST_LOGIN = `${PREFIX}REQUEST_LOGIN`;

export const REQUEST_USER_SIGNUP = `${PREFIX}REQUEST_USER_SIGNUP`;
export const RECEIVE_USER_SIGNUP = `${PREFIX}RECEIVE_USER_SIGNUP`;